# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

reduceGeneExpression <- function(expression, reduced_dim = 30L, method = 1L, iters = 10L) {
    .Call(`_ACTIONet_reduceGeneExpression`, expression, reduced_dim, method, iters)
}

runsimplexRegression <- function(A, B) {
    .Call(`_ACTIONet_runsimplexRegression`, A, B)
}

runSPA <- function(A, k) {
    .Call(`_ACTIONet_runSPA`, A, k)
}

runAA <- function(A, W0) {
    .Call(`_ACTIONet_runAA`, A, W0)
}

runACTION <- function(S_r, k_min = 2L, k_max = 20L, thread_no = 4L) {
    .Call(`_ACTIONet_runACTION`, S_r, k_min, k_max, thread_no)
}

