# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

reduceGeneExpression <- function(expression, reduced_dim = 30L, method = 1L, iters = 10L) {
    .Call(`_ACTIONet_reduceGeneExpression`, expression, reduced_dim, method, iters)
}

runsimplexRegression <- function(A, B) {
    .Call(`_ACTIONet_runsimplexRegression`, A, B)
}

runSPA <- function(A, k) {
    .Call(`_ACTIONet_runSPA`, A, k)
}

runAA <- function(A, W0) {
    .Call(`_ACTIONet_runAA`, A, W0)
}

runACTION <- function(S_r, k_min = 2L, k_max = 20L, thread_no = 4L) {
    .Call(`_ACTIONet_runACTION`, S_r, k_min, k_max, thread_no)
}

frSVD <- function(A, dim, iters = 5L, seed = 0L) {
    .Call(`_ACTIONet_frSVD`, A, dim, iters, seed)
}

set_seed <- function(seed) {
    invisible(.Call(`_ACTIONet_set_seed`, seed))
}

computeFullDist <- function(H_stacked, thread_no = 4L, verbose = 1L) {
    .Call(`_ACTIONet_computeFullDist`, H_stacked, thread_no, verbose)
}

computeNearestDist <- function(H_stacked, kNN, thread_no = 4L) {
    .Call(`_ACTIONet_computeNearestDist`, H_stacked, kNN, thread_no)
}

smoothKNN <- function(D, thread_no = 4L) {
    .Call(`_ACTIONet_smoothKNN`, D, thread_no)
}

computeNearestDist_edgeList <- function(H_stacked, kNN, thread_no = 4L) {
    .Call(`_ACTIONet_computeNearestDist_edgeList`, H_stacked, kNN, thread_no)
}

buildACTIONet <- function(H_stacked, kNN = 30L, thread_no = 8L) {
    .Call(`_ACTIONet_buildACTIONet`, H_stacked, kNN, thread_no)
}

buildAdaptiveACTIONet <- function(H_stacked, LC = 1.0, epsilon = 0.0, thread_no = 8L) {
    .Call(`_ACTIONet_buildAdaptiveACTIONet`, H_stacked, LC, epsilon, thread_no)
}

layoutACTIONet <- function(G, S_r, compactness_level = 1.0, n_epochs = 500L, thread_no = 8L) {
    .Call(`_ACTIONet_layoutACTIONet`, G, S_r, compactness_level, n_epochs, thread_no)
}

reconstructArchetypes <- function(S, C_trace, H_trace, z_threshold = 1.0) {
    .Call(`_ACTIONet_reconstructArchetypes`, S, C_trace, H_trace, z_threshold)
}

extractArchetypeAssociatedSamples <- function(G, H_stacked, alpha = 0.85) {
    .Call(`_ACTIONet_extractArchetypeAssociatedSamples`, G, H_stacked, alpha)
}

assessFeatureSets <- function(S, index_sets, rand_perm = 100L) {
    .Call(`_ACTIONet_assessFeatureSets`, S, index_sets, rand_perm)
}

assessFeatureSets_archs <- function(archetype_profile, index_sets, rand_perm = 100L) {
    .Call(`_ACTIONet_assessFeatureSets_archs`, archetype_profile, index_sets, rand_perm)
}

assessFeatureSets_decoupled <- function(archetype_profile, H_stacked, index_sets, rand_perm = 100L) {
    .Call(`_ACTIONet_assessFeatureSets_decoupled`, archetype_profile, H_stacked, index_sets, rand_perm)
}

computeAutocorrelation <- function(G, scores, rand_perm = 100L, num_shuffles = 10000L) {
    .Call(`_ACTIONet_computeAutocorrelation`, G, scores, rand_perm, num_shuffles)
}

phenotypeEnrichment <- function(H_stacked, phenotype_associations, rand_perm_no) {
    .Call(`_ACTIONet_phenotypeEnrichment`, H_stacked, phenotype_associations, rand_perm_no)
}

MWM <- function(G) {
    .Call(`_ACTIONet_MWM`, G)
}

batchPR <- function(G, U, alpha = 0.85, thread_no = 8L, tol = 1e-6) {
    .Call(`_ACTIONet_batchPR`, G, U, alpha, thread_no, tol)
}

sweepcut <- function(A, s) {
    .Call(`_ACTIONet_sweepcut`, A, s)
}

mergeArchetypes <- function(C_stacked, H_stacked) {
    .Call(`_ACTIONet_mergeArchetypes`, C_stacked, H_stacked)
}

signed_cluster <- function(A, resolution_parameter = 1.0, seed = 0L) {
    .Call(`_ACTIONet_signed_cluster`, A, resolution_parameter, seed)
}

unsigned_cluster <- function(A, resolution_parameter = 1.0, seed = 0L) {
    .Call(`_ACTIONet_unsigned_cluster`, A, resolution_parameter, seed)
}

Rank1_matching <- function(u, v, u_threshold = 0, v_threshold = 0) {
    .Call(`_ACTIONet_Rank1_matching`, u, v, u_threshold, v_threshold)
}

